In [1]:
%%time
import tensorflow as tf
import numpy as np
print(tf.__version__)

C:\Users\metya\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.9.0
Wall time: 3.18 s


In [2]:
tf.Graph()

In [3]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [6]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.88779783 0.9995593  0.15354097]
[0.402539   0.7466345  0.18403745]
(array([1.0259109, 1.5241404, 1.0161453], dtype=float32), array([2.0259109, 2.5241404, 2.0161452], dtype=float32))


In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [9]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [10]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [11]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-0.03551756  0.86909735  0.29059976]
[-0.5752694  -0.04043542 -0.14040105]
[-1.8306396  0.5925847  0.8758052]
[ 0.4816003  -2.5911448   0.61039466]
[0.22580892 1.659448   1.1092222 ]
[-0.8010745 -0.6309554 -1.1165694]
[-0.04138372  1.2136327   0.13442184]
[-1.6996489  -0.44398734 -1.3547816 ]
[-0.99797904  0.12640646 -0.12847602]
[ 0.9065686  -0.65298986  0.22719783]


In [12]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [13]:
init = tf.global_variables_initializer()
sess.run(init)

In [14]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[-1.9988847]
 [-7.050103 ]]


In [15]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[-3.0810857]
 [-8.495519 ]]


In [16]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [17]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [18]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


In [19]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [20]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [21]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[-1.1782258]
 [-2.3564515]
 [-3.5346773]
 [-4.712903 ]]


In [22]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

2.129362


In [23]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [24]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

2.129362
1.5130563
1.0852017
0.78811157
0.5817571
0.43836352
0.33865827
0.2692687
0.22091582
0.18716103
0.16353673
0.14694305
0.13522892
0.12690187
0.12092617
0.116583206
0.11337437
0.110953614
0.10908089
0.10758957
0.10636403
0.10532409
0.104414016
0.10359521
0.102840856
0.10213234
0.101456724
0.100805014
0.10017104
0.09955043
0.09894016
0.09833814
0.097742975
0.09715353
0.09656918
0.09598939
0.09541382
0.09484218
0.09427433
0.093710095
0.09314943
0.09259224
0.09203847
0.09148803
0.09094095
0.09039719
0.089856654
0.08931941
0.08878533
0.088254474
0.087726824
0.08720231
0.08668095
0.086162664
0.08564753
0.08513545
0.08462646
0.08412047
0.083617546
0.08311762
0.08262066
0.08212668
0.08163564
0.08114755
0.080662385
0.08018014
0.07970072
0.07922424
0.07875055
0.07827972
0.07781168
0.07734647
0.076884024
0.07642434
0.075967416
0.07551322
0.07506174
0.074612975
0.07416686
0.07372342
0.07328263
0.07284449
0.072408974
0.07197605
0.07154572
0.07111795
0.07069275
0.07027009
0.06984996
0.0694323

In [28]:
p = tf.placeholder(tf.float32)
t = p + 1.0
# t.eval(session=sess)  # This will fail, since the placeholder did not get a value.
t.eval(feed_dict={p:2.0})  # This will succeed because we're feeding a value
                           # to the placeholder.

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [29]:
my_variable = tf.get_variable("my_variable", [1, 2, 3])

In [30]:
my_int_variable = tf.get_variable("my_int_variable", [1, 2, 3], dtype=tf.int32,
  initializer=tf.zeros_initializer)

In [31]:
other_variable = tf.get_variable("other_variable", dtype=tf.int32,
  initializer=tf.constant([23, 42]))

In [32]:
my_local = tf.get_variable("my_local", shape=(),
collections=[tf.GraphKeys.LOCAL_VARIABLES])

In [33]:
my_non_trainable = tf.get_variable("my_non_trainable",
                                   shape=(),
                                   trainable=False)

In [34]:
tf.add_to_collection("my_collection_name", my_local)

In [35]:
tf.get_collection("my_collection_name")

[<tf.Variable 'my_local:0' shape=() dtype=float32_ref>]

In [39]:
sess.run(tf.global_variables_initializer())
# Now all variables are initialized.
sess.run(my_variable.initializer)

In [40]:
print(sess.run(tf.report_uninitialized_variables()))

[b'my_local']


In [47]:
v = tf.get_variable("v", shape=(), initializer=tf.zeros_initializer())
assignment = v.assign_add(1)
tf.global_variables_initializer().run()

ValueError: Variable v already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
